use_frameworks!



platform :ios, '10.0'

target 'YYComponents_Example' do
  pod 'YYComponents', :path => '../'
#  pod 'YYComponents.h'
#  pod 'YYComponents.h', :git => 'https://github.com/Jentlezhi/YYComponents.git',:tag => ‘0.1.1’
#  pod 'YYComponents'
  pod 'Masonry'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'MJRefresh', '3.5.0'
  pod 'ReactiveObjC'

  target 'YYComponents_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|

    installer.generated_projects.each do |project|

          project.targets.each do |target|

              target.build_configurations.each do |config|

                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'

               end
        end
   end
end
